### PR TITLE
Revamp application

### PR DESCRIPTION
**Pull request by comran**

### CODE REVIEW

**Comment by comran** [comment]
Still a working progress so don't merge with master -- will update with screenshots once I develop this more.

**Comment by comran** [comment]
Should be ready now. Some stuff that's included in this commit:
- Uses tabbed layout
- Fixed schedule/DJ list crashes when loading large images
- Random style updates
- Stream can now run in background.

Images of updates:
https://drive.google.com/open?id=1ggWBrz1tuSUv8ztGWa0adD1LY4RXYp-A

**Review by etehrani — DISMISSED** [review]
Tab layout and updated formatting look nice. Need to update Stream page design before releasing Beta (preferably by next week). I'll be working on that too.

**Comment by arjunr00** [comment]
Merging into `master` since there doesn't seem any reason for not doing so.
This PR includes the following changes:

- [#7] Drastic overhaul (visual and behind the scenes) of app
- [#10] Switch from port 8000 to https to avoid UCLA_WEB issues
- [#11] Added chat functionality

See the linked PRs for a closer overview of these changes.

**Review by tanzeelak — APPROVED** [review]
inspired

**Pull request merged**
